platform :ios, '10.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!


target 'Chapter6ObjectWithLabels' do
        pod 'GoogleMLKit/ObjectDetection'
        pod 'GoogleMLKit/ImageLabeling'
end

